In [22]:
pip install numpy

^C
Note: you may need to restart the kernel to use updated packages.



[notice] A new release of pip is available: 24.0 -> 24.2
[notice] To update, run: python.exe -m pip install --upgrade pip


In [ ]:
import numpy

In [ ]:
print(numpy.__version__)

2.0.1


In [ ]:
import numpy as np

In [ ]:
a = np.array
print(a)

<built-in function array>


In [ ]:
#Defining an array
a = np.array([1,2,3])
print(a)

[1 2 3]


In [ ]:
a = np.array([1,2,3])
print(a.dtype)
print(type(a))
print(a.ndim)

int64
<class 'numpy.ndarray'>
1


In [ ]:
a = np.array([[1,2,3],[4,5,6]])
print(a)
print(a.dtype)
print(type(a))
print(a.ndim)

[[1 2 3]
 [4 5 6]]
int64
<class 'numpy.ndarray'>
2


In [ ]:
#Defining Complex numbers
a = np.array([1,2,3], complex)
print(a)

[1.+0.j 2.+0.j 3.+0.j]


In [ ]:
#Printing size and shape
a = np.array([[1,2,3,4,5,6]])
print(a.size) # no.of elements
print(a.shape) #(rows,columns)

6
(1, 6)


In [ ]:
arr = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
print(arr)
print(arr.size)
print(arr.shape)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
12
(3, 4)


In [ ]:
#Reshape - Change of rows and columns
a = np.array([[1,2],[3,4],[5,6]])
print('Original array')
print(a)

a = a.reshape(2,3)
print('Reshaped array')
print(a)

Original array
[[1 2]
 [3 4]
 [5 6]]
Reshaped array
[[1 2 3]
 [4 5 6]]


In [ ]:
#Accessing of elements
a = np.array([[1,2],[3,4],[5,6]])
print(a)

print(a[0,1])
print(a[2,1])

[[1 2]
 [3 4]
 [5 6]]
2
6


In [ ]:
#Basic functions like min,max and sum in 1D-array
a = np.array([1,2,3,50,4,45,4])
print(a)
print('Maximum number: ', a.max())
print('Minimum number: ', a.min())
print('Sum of all values: ', a.sum())

[ 1  2  3 50  4 45  4]
Maximum number:  50
Minimum number:  1
Sum of all values:  109


In [ ]:
np.identity(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [ ]:
b = np.zeros((5,2))
print(b)

[[0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]]


In [ ]:
b = np.ones((5,6))
print(b)

[[1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]]


In [ ]:
a = np.array([[1,2],[3,4],[5,6]])
print(a) 

[[1 2]
 [3 4]
 [5 6]]


In [ ]:
#Basic functions like min,max and sum in 2D-array
a = np.array([[1,2],[3,4],[5,6]])
print(a)
print("Max number in column:", a.max(axis=0))
print('Min number in row:',a.min(axis=1))
print('Sum of all values in rows:',a.sum(axis=1))

[[1 2]
 [3 4]
 [5 6]]
Max number in column: [5 6]
Min number in row: [1 3 5]
Sum of all values in rows: [ 3  7 11]


In [ ]:
# randn --> generates random number between (-1,0,1)

a = np.random.randn(5,3)
print(a)

[[-1.08709108  1.29106448 -1.19474468]
 [-1.76192708 -0.08095763 -0.04602688]
 [-1.20015818 -1.7034742   0.25974354]
 [-0.73612065 -0.39581361 -0.67173748]
 [ 0.72029861 -0.88870153 -1.37824116]]


In [ ]:
# Arithmetic operation
    #Addition
    #Subtraction
    #Multiplication
    #Division
a = np.array([[1,2,3],[4,5,6]])
b = np.array([[1,2,3],[10,5,15]])

print("Sum of a and b:\n ", a+b)
print('*********************************')
print("Sub of a and b:\n ", a-b)
print('*********************************')
print("Product of a and b:\n", a*b)
print('*********************************')
print("division of a and b: \n", a/b)

Sum of a and b:
  [[ 2  4  6]
 [14 10 21]]
*********************************
Sub of a and b:
  [[ 0  0  0]
 [-6  0 -9]]
*********************************
Product of a and b:
 [[ 1  4  9]
 [40 25 90]]
*********************************
division of a and b: 
 [[1.  1.  1. ]
 [0.4 1.  0.4]]


In [ ]:
#Ranging function ---> range()

for i in range(11):
    print(i, end=' ')

0 1 2 3 4 5 6 7 8 9 10 

In [ ]:
# Ranging function in numpy --> arange()

print(np.arange(12))

[ 0  1  2  3  4  5  6  7  8  9 10 11]


In [ ]:
print(np.arange(12).reshape(3,4))

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


In [23]:
arr = np.arange(12).reshape(2,2,3) # --> 2*3, 2*3 (generates 2 matrices)
print(arr)
print('*********************************')
print(arr[0])
print('*********************************')
print(arr[1])
print('*********************************')
print(arr[0][1])
print('*********************************')
print(arr[0][1][2])

[[[ 0  1  2]
  [ 3  4  5]]

 [[ 6  7  8]
  [ 9 10 11]]]
*********************************
[[0 1 2]
 [3 4 5]]
*********************************
[[ 6  7  8]
 [ 9 10 11]]
*********************************
[3 4 5]
*********************************
5


In [25]:
#slicing with arange()
print(np.arange(12))
print(np.arange(12)[0:7])
print(np.arange(12)[0:7][1])

[ 0  1  2  3  4  5  6  7  8  9 10 11]
[0 1 2 3 4 5 6]
1


In [26]:
log = np.logspace(10,20, num = 5)
print(log)

[1.00000000e+10 3.16227766e+12 1.00000000e+15 3.16227766e+17
 1.00000000e+20]


In [27]:
arr = np.linspace(10,20,5)
print(arr)

[10.  12.5 15.  17.5 20. ]


# Numpy Broadcasting

In [28]:
a = np.array([1,2,3,4,5,6,7])
b = np.array([2,4,6,8,10,12,14])
c = a*b
print(c)

[ 2  8 18 32 50 72 98]


In [29]:
a = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
b = np.array([2,4,6,8])
print(a)
print('*********************************')
print(b)
print('*********************************')
print(a+b)
print('*********************************')
print(a-b)
print('*********************************')
print(a*b)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
*********************************
[2 4 6 8]
*********************************
[[ 3  6  9 12]
 [ 7 10 13 16]
 [11 14 17 20]]
*********************************
[[-1 -2 -3 -4]
 [ 3  2  1  0]
 [ 7  6  5  4]]
*********************************
[[ 2  8 18 32]
 [10 24 42 64]
 [18 40 66 96]]


In [30]:
arr1 = np.arange(15).reshape(5,3)
print(arr1)
print('*********************************')
arr2 = np.arange(5).reshape(5,1)
print(arr2)
print('*********************************')
print(arr1 + arr2)

[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]
 [12 13 14]]
*********************************
[[0]
 [1]
 [2]
 [3]
 [4]]
*********************************
[[ 0  1  2]
 [ 4  5  6]
 [ 8  9 10]
 [12 13 14]
 [16 17 18]]


In [31]:
print(np.array(['apple','banana','cherry']))
print('*********************************')
print(np.array([['welcome'],['hi']]))

['apple' 'banana' 'cherry']
*********************************
[['welcome']
 ['hi']]


In [32]:
print(np.char.add(['welcome'],['hi']))

['welcomehi']


In [33]:
arr = np.array(["A","B","C"])
result = np.char.multiply(arr,3)
print(result)

['AAA' 'BBB' 'CCC']


In [34]:
# Round function ---> around()

arr = np.array([12.2, 90.12, 12.54789, 52.86745678])
print(arr)
print("Rounding function: ", np.around(arr))
print('*********************************')
print("With decimal:",np.around(arr, 2) )

[12.2        90.12       12.54789    52.86745678]
Rounding function:  [12. 90. 13. 53.]
*********************************
With decimal: [12.2  90.12 12.55 52.87]


In [35]:
arr = np.array([12.2, 90.12, 12.54, 52.85])
print("Floor: ", np.floor(arr))
print("Ceil: ", np.ceil(arr))

Floor:  [12. 90. 12. 52.]
Ceil:  [13. 91. 13. 53.]


In [36]:
# Mean, Median, Average

a = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(a)
print('*********************************')
print(np.median(a))
print('*********************************')
print(np.median(a,0)) #--> axis = columns
print('*********************************')
print(np.median(a,1)) # --> axis = rows
print('*********************************')
print(np.mean(a))
print('*********************************')
print(np.average(a))

[[1 2 3]
 [4 5 6]
 [7 8 9]]
*********************************
5.0
*********************************
[4. 5. 6.]
*********************************
[2. 5. 8.]
*********************************
5.0
*********************************
5.0


In [37]:
a = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(a)
print('*********************************')
at = a.T # Transpose --> rows changes to columns, columns changes to rows
print(at)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
*********************************
[[1 4 7]
 [2 5 8]
 [3 6 9]]


In [38]:
a = np.array([[100,200],[30,40]])
b = np.array([[10,20],[50,60]])
print(a)
print('*********************************')
print(b)
print('*********************************')
print(a*b) # --> Multiplication
print('*********************************')
x = np.dot(a,b) # --> Dot product
print(x)

[[100 200]
 [ 30  40]]
*********************************
[[10 20]
 [50 60]]
*********************************
[[1000 4000]
 [1500 2400]]
*********************************
[[11000 14000]
 [ 2300  3000]]
